version: "3.6"

services:
  peripheral-manager-bluetooth:
    build: .
    restart: on-failure
    network_mode: "host"
    environment:
      - NUVLABOX_UUID=${NUVLABOX_UUID}
      - NUVLA_ENDPOINT=${NUVLA_ENDPOINT:-nuvla.io}
      - NUVLA_ENDPOINT_INSECURE=${NUVLA_ENDPOINT_INSECURE:-False}
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    labels:
      - nuvlabox.component=True
      - nuvlabox.deployment=production
